# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwiterFromLetBuild' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwiterFromLetBuild
pod 'SnapKit'
pod 'RxSwift'
pod 'RxCocoa'
pod 'TRON'

end
